# Tested with "ubuntu/bionic64 v20200206.0.0" Vagrant box.
#
######################################################################
############################# Important! #############################
######################################################################
#
# TCP needs to be explicitly specified in order to check the databases
# from the host OS, here is the working command:
# mysql -h localhost --protocol tcp -uroot -p'123456' -e 'SHOW DATABASES;'
#
$confluence_inst_script = <<-SCRIPT
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y mysql-server
sed -i "s/bind-address\t\t= 127.0.0.1/# bind-address\t\t= 127.0.0.1/" /etc/mysql/mysql.conf.d/mysqld.cnf
mysql -u root -p --skip-password -e "CREATE DATABASE CONFLUENCE CHARACTER SET utf8mb4 COLLATE utf8mb4_bin; GRANT ALL PRIVILEGES ON CONFLUENCE.* TO 'root'@'localhost'; ALTER USER 'root'@'localhost' IDENTIFIED BY '123456'; CREATE USER 'root' IDENTIFIED BY '123456'; GRANT ALL PRIVILEGES ON *.* TO 'root';"
/etc/init.d/mysql restart
cd /vagrant
wget --no-clobber https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.3.1-x64.bin
chmod u+x atlassian-confluence-7.3.1-x64.bin
./atlassian-confluence-7.3.1-x64.bin -q -varfile response.varfile
wget --no-clobber https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.48.zip
apt-get install -y unzip
unzip -n mysql-connector-java-5.1.48.zip
bash /opt/atlassian/confluence_7_3_1/bin/stop-confluence.sh
cp -v mysql-connector-java-5.1.48/mysql-connector-java-5.1.48-bin.jar /opt/atlassian/confluence_7_3_1/confluence/WEB-INF/lib
bash /opt/atlassian/confluence_7_3_1/bin/start-confluence.sh
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = 3072 # Default 1024 MB aren't enough even closely, Java needs a lot of memory :)
  end
  config.vm.provision "shell", inline: $confluence_inst_script
  config.vm.network "forwarded_port", guest: 8090, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 3306, host: 3306, host_ip: "127.0.0.1"
end
